CREATE TABLE ARTICLE
(Article_ID SERIAL PRIMARY KEY,
Date_published DATE NOT NULL,
Author VARCHAR(100) NOT NULL,
Title VARCHAR(1000) NOT NULL,
Body TEXT NOT NULL);

CREATE TABLE TAG_CATEGORY
(Category_name VARCHAR(50) NOT NULL,
PRIMARY KEY(Category_name));

CREATE TABLE TAG
(Tag_name VARCHAR(100) NOT NULL,
Category_name VARCHAR(50) NOT NULL,
PRIMARY KEY (Tag_name),
FOREIGN KEY (Category_name) REFERENCES TAG_CATEGORY (Category_name));

CREATE TABLE CLASSIFIED_AS
(Article_ID INTEGER NOT NULL,
Tag_name VARCHAR(100) NOT NULL,
PRIMARY KEY (Article_ID, Tag_name),
FOREIGN KEY (Article_ID) REFERENCES ARTICLE (Article_ID),
FOREIGN KEY (Tag_name) REFERENCES TAG (Tag_name));
